/// @description Insert description here
// You can write your code in this editor
if(global.lifer <=82) sprite_index = spr_guiHPBar1
if(global.lifer <=81) sprite_index = spr_guiHPBar2
if(global.lifer <=80) sprite_index = spr_guiHPBar3
if(global.lifer <=79) sprite_index = spr_guiHPBar4
if(global.lifer <=78) sprite_index = spr_guiHPBar5
if(global.lifer <=77) sprite_index = spr_guiHPBar6
if(global.lifer <=76) sprite_index = spr_guiHPBar7
if(global.lifer <=75) sprite_index = spr_guiHPBar8
if(global.lifer <=74) sprite_index = spr_guiHPBar9
if(global.lifer <=73) sprite_index = spr_guiHPBar10
if(global.lifer <=72) sprite_index = spr_guiHPBar11
if(global.lifer <=71) sprite_index = spr_guiHPBar12
if(global.lifer <=70) sprite_index = spr_guiHPBar13
if(global.lifer <=69) sprite_index = spr_guiHPBar14
if(global.lifer <=68) sprite_index = spr_guiHPBar15
if(global.lifer <=67) sprite_index = spr_guiHPBar16
if(global.lifer <=66) sprite_index = spr_guiHPBar17
if(global.lifer <=65) sprite_index = spr_guiHPBar18
if(global.lifer <=64) sprite_index = spr_guiHPBar19
if(global.lifer <=63) sprite_index = spr_guiHPBar20
if(global.lifer <=62) sprite_index = spr_guiHPBar21
if(global.lifer <=61) sprite_index = spr_guiHPBar22
if(global.lifer <=60) sprite_index = spr_guiHPBar23
if(global.lifer <=59) sprite_index = spr_guiHPBar24
if(global.lifer <=58) sprite_index = spr_guiHPBar25
if(global.lifer <=57) sprite_index = spr_guiHPBar26
if(global.lifer <=56) sprite_index = spr_guiHPBar27
if(global.lifer <=55) sprite_index = spr_guiHPBar28
if(global.lifer <=54) sprite_index = spr_guiHPBar29
if(global.lifer <=53) sprite_index = spr_guiHPBar31
if(global.lifer <=52) sprite_index = spr_guiHPBar32
if(global.lifer <=51) sprite_index = spr_guiHPBar33
if(global.lifer <=50) sprite_index = spr_guiHPBar34
if(global.lifer <=49) sprite_index = spr_guiHPBar35
if(global.lifer <=48) sprite_index = spr_guiHPBar36
if(global.lifer <=47) sprite_index = spr_guiHPBar37
if(global.lifer <=46) sprite_index = spr_guiHPBar38
if(global.lifer <=45) sprite_index = spr_guiHPBar39
if(global.lifer <=44) sprite_index = spr_guiHPBar40
if(global.lifer <=43) sprite_index = spr_guiHPBar41
if(global.lifer <=42) sprite_index = spr_guiHPBar42
if(global.lifer <=41) sprite_index = spr_guiHPBar43
if(global.lifer <=40) sprite_index = spr_guiHPBar44
if(global.lifer <=39) sprite_index = spr_guiHPBar45
if(global.lifer <=38) sprite_index = spr_guiHPBar46
if(global.lifer <=37) sprite_index = spr_guiHPBar47
if(global.lifer <=36) sprite_index = spr_guiHPBar48
if(global.lifer <=35) sprite_index = spr_guiHPBar49
if(global.lifer <=34) sprite_index = spr_guiHPBar50
if(global.lifer <=33) sprite_index = spr_guiHPBar51
if(global.lifer <=32) sprite_index = spr_guiHPBar52
if(global.lifer <=31) sprite_index = spr_guiHPBar53
if(global.lifer <=30) sprite_index = spr_guiHPBar54
if(global.lifer <=29) sprite_index = spr_guiHPBar55
if(global.lifer <=28) sprite_index = spr_guiHPBar56
if(global.lifer <=27) sprite_index = spr_guiHPBar57
if(global.lifer <=26) sprite_index = spr_guiHPBar58
if(global.lifer <=25) sprite_index = spr_guiHPBar59
if(global.lifer <=24) sprite_index = spr_guiHPBar60
if(global.lifer <=23) sprite_index = spr_guiHPBar61
if(global.lifer <=21) sprite_index = spr_guiHPBar62
if(global.lifer <=20) sprite_index = spr_guiHPBar63
if(global.lifer <=19) sprite_index = spr_guiHPBar64
if(global.lifer <=18) sprite_index = spr_guiHPBar65
if(global.lifer <=17) sprite_index = spr_guiHPBar66
if(global.lifer <=16) sprite_index = spr_guiHPBar67
if(global.lifer <=15) sprite_index = spr_guiHPBar68
if(global.lifer <=14) sprite_index = spr_guiHPBar69
if(global.lifer <=13) sprite_index = spr_guiHPBar70
if(global.lifer <=12) sprite_index = spr_guiHPBar71
if(global.lifer <=11) sprite_index = spr_guiHPBar72
if(global.lifer <=10) sprite_index = spr_guiHPBar73
if(global.lifer <=9) sprite_index = spr_guiHPBar74
if(global.lifer <=8) sprite_index = spr_guiHPBar75
if(global.lifer <=7) sprite_index = spr_guiHPBar76
if(global.lifer <=6) sprite_index = spr_guiHPBar77
if(global.lifer <=5) sprite_index = spr_guiHPBar78
if(global.lifer <=4) sprite_index = spr_guiHPBar79
if(global.lifer <=3) sprite_index = spr_guiHPBar80
if(global.lifer <=2) sprite_index = spr_guiHPBar81
if(global.lifer <=1) sprite_index = spr_guiHPBar82
if(global.lifer <=0) 
{
sprite_index = spr_guiHPBar83
game_end()
}