/// @description Insert description here
// You can write your code in this editor
if(global.life <=82) sprite_index = spr_guiHPBar1
if(global.life <=81) sprite_index = spr_guiHPBar2
if(global.life <=80) sprite_index = spr_guiHPBar3
if(global.life <=79) sprite_index = spr_guiHPBar4
if(global.life <=78) sprite_index = spr_guiHPBar5
if(global.life <=77) sprite_index = spr_guiHPBar6
if(global.life <=76) sprite_index = spr_guiHPBar7
if(global.life <=75) sprite_index = spr_guiHPBar8
if(global.life <=74) sprite_index = spr_guiHPBar9
if(global.life <=73) sprite_index = spr_guiHPBar10
if(global.life <=72) sprite_index = spr_guiHPBar11
if(global.life <=71) sprite_index = spr_guiHPBar12
if(global.life <=70) sprite_index = spr_guiHPBar13
if(global.life <=69) sprite_index = spr_guiHPBar14
if(global.life <=68) sprite_index = spr_guiHPBar15
if(global.life <=67) sprite_index = spr_guiHPBar16
if(global.life <=66) sprite_index = spr_guiHPBar17
if(global.life <=65) sprite_index = spr_guiHPBar18
if(global.life <=64) sprite_index = spr_guiHPBar19
if(global.life <=63) sprite_index = spr_guiHPBar20
if(global.life <=62) sprite_index = spr_guiHPBar21
if(global.life <=61) sprite_index = spr_guiHPBar22
if(global.life <=60) sprite_index = spr_guiHPBar23
if(global.life <=59) sprite_index = spr_guiHPBar24
if(global.life <=58) sprite_index = spr_guiHPBar25
if(global.life <=57) sprite_index = spr_guiHPBar26
if(global.life <=56) sprite_index = spr_guiHPBar27
if(global.life <=55) sprite_index = spr_guiHPBar28
if(global.life <=54) sprite_index = spr_guiHPBar29
if(global.life <=53) sprite_index = spr_guiHPBar31
if(global.life <=52) sprite_index = spr_guiHPBar32
if(global.life <=51) sprite_index = spr_guiHPBar33
if(global.life <=50) sprite_index = spr_guiHPBar34
if(global.life <=49) sprite_index = spr_guiHPBar35
if(global.life <=48) sprite_index = spr_guiHPBar36
if(global.life <=47) sprite_index = spr_guiHPBar37
if(global.life <=46) sprite_index = spr_guiHPBar38
if(global.life <=45) sprite_index = spr_guiHPBar39
if(global.life <=44) sprite_index = spr_guiHPBar40
if(global.life <=43) sprite_index = spr_guiHPBar41
if(global.life <=42) sprite_index = spr_guiHPBar42
if(global.life <=41) sprite_index = spr_guiHPBar43
if(global.life <=40) sprite_index = spr_guiHPBar44
if(global.life <=39) sprite_index = spr_guiHPBar45
if(global.life <=38) sprite_index = spr_guiHPBar46
if(global.life <=37) sprite_index = spr_guiHPBar47
if(global.life <=36) sprite_index = spr_guiHPBar48
if(global.life <=35) sprite_index = spr_guiHPBar49
if(global.life <=34) sprite_index = spr_guiHPBar50
if(global.life <=33) sprite_index = spr_guiHPBar51
if(global.life <=32) sprite_index = spr_guiHPBar52
if(global.life <=31) sprite_index = spr_guiHPBar53
if(global.life <=30) sprite_index = spr_guiHPBar54
if(global.life <=29) sprite_index = spr_guiHPBar55
if(global.life <=28) sprite_index = spr_guiHPBar56
if(global.life <=27) sprite_index = spr_guiHPBar57
if(global.life <=26) sprite_index = spr_guiHPBar58
if(global.life <=25) sprite_index = spr_guiHPBar59
if(global.life <=24) sprite_index = spr_guiHPBar60
if(global.life <=23) sprite_index = spr_guiHPBar61
if(global.life <=21) sprite_index = spr_guiHPBar62
if(global.life <=20) sprite_index = spr_guiHPBar63
if(global.life <=19) sprite_index = spr_guiHPBar64
if(global.life <=18) sprite_index = spr_guiHPBar65
if(global.life <=17) sprite_index = spr_guiHPBar66
if(global.life <=16) sprite_index = spr_guiHPBar67
if(global.life <=15) sprite_index = spr_guiHPBar68
if(global.life <=14) sprite_index = spr_guiHPBar69
if(global.life <=13) sprite_index = spr_guiHPBar70
if(global.life <=12) sprite_index = spr_guiHPBar71
if(global.life <=11) sprite_index = spr_guiHPBar72
if(global.life <=10) sprite_index = spr_guiHPBar73
if(global.life <=9) sprite_index = spr_guiHPBar74
if(global.life <=8) sprite_index = spr_guiHPBar75
if(global.life <=7) sprite_index = spr_guiHPBar76
if(global.life <=6) sprite_index = spr_guiHPBar77
if(global.life <=5) sprite_index = spr_guiHPBar78
if(global.life <=4) sprite_index = spr_guiHPBar79
if(global.life <=3) sprite_index = spr_guiHPBar80
if(global.life <=2) sprite_index = spr_guiHPBar81
if(global.life <=1) sprite_index = spr_guiHPBar82
if(global.life <=0)
{
 sprite_index = spr_guiHPBar83
 game_end()
}